### ISSUE TITLE
Update to semver v2.0.0

### ISSUE THREAD

**Issue by theory** [theory/semver#2]
[Semantic Versioning 2.0.0](http://semver.org) has been released. To update the Perl module, we would need to:
- Allow dot-delimited patch versions.
- Allow "build metadata" after the patch version, also dot-delimited, and delimited from the patch version by a `+`.
- Modify the sort ordering of the patch version as specified:

> 1. Precedence refers to how versions are compared to each other when ordered.
>    Precedence MUST be calculated by separating the version into major, minor, patch
>    and pre-release identifiers in that order (Build metadata does not figure 
>    into precedence). Precedence is determined by the first difference when
>    comparing each of these identifiers from left to right as follows: Major, minor,
>    and patch versions are always compared numerically. Example: 1.0.0 < 2.0.0 <
>    2.1.0 < 2.1.1. When major, minor, and patch are equal, a pre-release version has
>    lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0. Precedence
>    for two pre-release versions with the same major, minor, and patch version MUST
>    be determined by comparing each dot separated identifier from left to right
>    until a difference is found as follows: identifiers consisting of only digits
>    are compared numerically and identifiers with letters or hyphens are compared
>    lexically in ASCII sort order. Numeric identifiers always have lower precedence
>    than non-numeric identifiers. A larger set of pre-release fields has a higher
>    precedence than a smaller set, if all of the preceding identifiers are equal.
>    Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta <
>    1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by hoppfrosch** [comment]
Any news on this? Would be great in conjunction with [GitVersion](https://github.com/GitTools/GitVersion)

**Comment by Relequestual** [comment]
Curious, what's the current state of this?

**Comment by theory** [comment]
Looks like it has been merged, but not released. @hoppfrosch: would you like to take maintainership? Do you have a PAUSE ID?

**Comment by Relequestual** [comment]
Last (and only) time I offered to take maint, I found it impossible to make the build and dist work, even with help from the faithful perl irc crew... tobyink module, much custom distzil stuff!

**Comment by theory** [comment]
Huh? It just has a `Build.PL`. No `dzil` stuff at all. Are you thinking of some other module, @Relequestual?

**Comment by Relequestual** [comment]
Last time I offered to take maint (on another project)*.

Sorry I assumed you might remember if someone offered to maint your module before or not, but I appreciate open source is vast! =]

**Comment by theory** [comment]
Yeah, this one is pretty simple.

**Comment by hoppfrosch** [comment]
I do not have a PAUSE ID - and I don't have any experience in releasing/maintaining things on CPAN.
But I think I might give it a try ...

**Comment by theory** [comment]
Hey @hoppfrosch, you can [request an account](
https://pause.perl.org/pause/query?ACTION=request_id). Let me know what username you end up with and I’ll add you as a co-maintainer. @johnpeacockmessagesystems: do you have an interest in co-maint, as well?

**Comment by hoppfrosch** [comment]
I now do have a PAUSE ID - my username is hopfrog (as this is "hoppfrosch" in english ;-))

**Comment by theory** [comment]
Okay, I’ve given you a commit bit and made you co-maintainer on CPAN, @hoppfrosch. If you think it’s ready to release, the process looks like this:

* Make sure all the tests pass
* Proofread Changes, making sure all changes since the last release are listed.
* Add a UTC 8601 timestamp for the new version to Changes
* Run `perl Build.PL && ./Build manifest && ./Build dist` to make the distribution
* Upload it to PAUSE
* Tag the release `git tag v0.7.0 -am 'Tag v0.7.0' && git push --tags`
* Incrment the version in preparation for the next release.

**Comment by hoppfrosch** [comment]
I'm done as far as I was sure to do (I've build the distribution)

What has to be uploaded? The *.tar.gz file only? What else?

To which folder I do have to upload to? (authors/id/H/HO/HOPFROG ?)

**Comment by theory** [comment]
All you have to do is log into [PAUSE](https://pause.perl.org/), hit the "Upload a file to CPAN" link, add the file under "Upload material", and hit the upload button. You'll receive confirmation that it was submitted via email, then you should get a second email a few minutes later confirming that it was successfully indexed. If it wasn't indexed, email me the error and we'll try to get it fixed.

**Comment by xtaran** [comment]
I see a version `0.7.0` with `Implemented Semantic Versioning 2.0.0 specification` in `Changes` on CPAN. So this seems to be fixed now. Cool! :+1:
